name: ReactCICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Build Docker Image
        run: |
          docker build -t fruit .

      - name: Run Docker Container
        run: |
          docker run -d --name mango -p 3001:3000 fruit
